version: '2'

services:
  flaskapp:
    build:
      context: .
      dockerfile: flaskapp.Dockerfile
    volumes:
      - './:/app'
    ports:
      - '80:5000'
    links:
      - bokehapp
  bokehapp:
    build:
      context: .
      dockerfile: bokehapp.Dockerfile
    ports:
      - '5006:5006'
    volumes:
      - './:/app'
